Display last event sessions on home screen
leonardoxh/race-control-tv pull request #71
Opened 2021-05-15 12:21 UTC by kleinMaggus

I've added the last event sessions to the home screen for faster access.

![Screenshot_Home_Last_Event](https://user-images.githubusercontent.com/3748388/118360506-3d168d80-b588-11eb-9eec-4d93a4eb9a5d.png)

Please test it espacially with schedule and update every one minute stuff. And if you have a smart idea on how to populate the rows (HomeFragment:89) in an easier and extensible way you're welcome :D

Let me know what your thoughts are :)

2021-05-25 07:51 UTC, leonardoxh commented
Hi, sorry for late reply, I am not sure about this feature itself, I think it is becoming a bit out of control on this part in terms of the simplicity I would like to keep.

2021-05-26 18:17 UTC, kleinMaggus commented
Hi, np. I like the idea of having fast access directly from the home screen. But if you want to keep it simple, we can remove the PR. 
For sure I will create another one with the requestFocus for the teaser image because it does not have the focus when I start my app 😅

2021-06-02 20:39 UTC, nilsnilsnils commented
I often watch the replay of the qualification or the race when I don't have time watching live. I would like to have fast access to current live session or quali and race replay of the last race. So 3 items would be enough for me. Its more important than old seasons. Therefore this pull request has my support.

I thank all of you for your great work :)

2021-06-04 14:44 UTC, leonardoxh requested changes
Ok, I have been thinking a lot and I am also in middle of job switching so pretty busy.

Hey I will test this PR this weekend and if all good let's merge it Monday (after the few changes requested)

2021-06-04 14:44 UTC, leonardoxh commented on app/src/main/java/fr/groggy/racecontrol/tv/ui/home/HomeActivity.kt
> +    lateinit var seasonService: SeasonService
internal ?

2021-06-04 14:44 UTC, leonardoxh commented on app/src/main/java/fr/groggy/racecontrol/tv/ui/home/HomeViewModel.kt
> +) : ViewModel() {
I guess this small change can just be reverted

2021-06-04 14:44 UTC, leonardoxh commented on app/src/main/java/fr/groggy/racecontrol/tv/ui/season/archive/SeasonArchiveFragment.kt
> +    private val archivesAdapter = ArrayObjectAdapter(listRowPresenter)
Inline this as 

`
private val archivesAdapter = ArrayObjectAdapter(CustomListRowPresenter())
`

2021-06-04 14:44 UTC, leonardoxh commented on app/src/main/java/fr/groggy/racecontrol/tv/ui/home/HomeFragment.kt
> +            val event = events[0]
I think there is a convenience method on arrays that is `events.first()`

2021-06-04 14:44 UTC, leonardoxh commented on app/src/main/java/fr/groggy/racecontrol/tv/ui/home/HomeFragment.kt
> +    private val homeEntriesAdapter = ArrayObjectAdapter(listRowPresenter)
Same (inline)

2021-06-04 14:44 UTC, leonardoxh commented on app/src/main/java/fr/groggy/racecontrol/tv/ui/home/HomeFragment.kt
> +    private var archivesRow: ListRow? = null
Is this variable used?

2021-06-09 09:03 UTC, merged